### ISSUE TITLE
To do: 

### ISSUE THREAD

**Issue by madeleinehickman** [nukhbahmajid/SDS220-FinalProject#1]
we each will take 50 of the movies from our n = 200 data set and will find for each one:
                  - the gender of the director (if you can't find it that's ok, it will just be missing data, type 0 for Male or 1 for F)
                  - the genre of the movie (COMEDY, ACTION, DRAMA, OTHER) (just make your best guess, don't take too long trying to figure out the genre

Christian is doing rows 1-50
Nukhbah 51-100
Annabel 101-150
Madeleine 151-200

find the info and enter it into the google sheet 

we start with a data set in r -> data set in excel -> data set in google sheets      [here we input our new data]     data set in google sheets -> data set in excel -> data set in r

Have a great weekend!

**Comment by nukhbahmajid** [comment]
genres to narrow down to: comedy, drama, action, other.
